include:
- ./bom.py
- ./requirements.txt
- ./build.sh
kind: ArchiveUploadSpec
name: bom-py-Qybq

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: bom
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://bom-py-Qybq
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-16T02:41:57Z"
