apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: bom
spec:
  createingress: true
  functionref:
    functionweights: null
    name: bom
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /bom
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /bom
