include:
- ./health.py
- ./requirements.txt
- ./build.sh
kind: ArchiveUploadSpec
name: health-py-vsm1

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: h
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://health-py-vsm1
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-16T03:03:57Z"
